// Generated by https://quicktype.io

export interface IngredientResponse {
    ingredients: Ingredient[];
}

export interface Ingredient {
    idIngredient:   string;
    strIngredient:  string;
    strDescription: string;
    strType:        string;
    strAlcohol:     string;
    strABV:         string;
}